version: '3.8'

services:
  backend:
    build: ./server
    container_name: myguideon-back
    ports:
      - "3000:3000"
    env_file:
       - ./server/.env.docker
    depends_on:
      - db
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  db:
    image: mysql:8.0
    container_name: myguideon-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: myguideon
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
